//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisOfertas.ServiceReporte {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReporte.WebServiceReporteSoap")]
    public interface WebServiceReporteSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/generarArchivo", ReplyAction="*")]
        void generarArchivo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/generarArchivo", ReplyAction="*")]
        System.Threading.Tasks.Task generarArchivoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceReporteSoapChannel : MisOfertas.ServiceReporte.WebServiceReporteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceReporteSoapClient : System.ServiceModel.ClientBase<MisOfertas.ServiceReporte.WebServiceReporteSoap>, MisOfertas.ServiceReporte.WebServiceReporteSoap {
        
        public WebServiceReporteSoapClient() {
        }
        
        public WebServiceReporteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceReporteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceReporteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceReporteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void generarArchivo() {
            base.Channel.generarArchivo();
        }
        
        public System.Threading.Tasks.Task generarArchivoAsync() {
            return base.Channel.generarArchivoAsync();
        }
    }
}
